/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmgmt_assignment2;

import java.awt.Color;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.*;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author maher
 */
public class AddEncounterAndVitals extends javax.swing.JFrame {

    /**
     * Creates new form AddEncounterAndVitals
     */
    public AddEncounterAndVitals() {
        initComponents();
        
        Color c = new Color(102,102,102);
        getContentPane().setBackground(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientID1 = new javax.swing.JLabel();
        PatientIDText = new javax.swing.JTextField();
        BloodPressureText = new javax.swing.JTextField();
        PatientID2 = new javax.swing.JLabel();
        PatientID3 = new javax.swing.JLabel();
        BodyTemperatureText = new javax.swing.JTextField();
        PulseRateText = new javax.swing.JTextField();
        PatientID4 = new javax.swing.JLabel();
        PatientID6 = new javax.swing.JLabel();
        EncounterText = new javax.swing.JTextField();
        PatientID5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DiagnosesText = new javax.swing.JTextArea();
        Submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PatientID1.setText("Patient ID");

        PatientID2.setText("Blood Pressure");

        PatientID3.setText("Body Temperature");

        PatientID4.setText("Pulse Rate");

        PatientID6.setText("Diagnosis");

        PatientID5.setText("Encounter Timestamp");

        DiagnosesText.setColumns(20);
        DiagnosesText.setRows(5);
        jScrollPane1.setViewportView(DiagnosesText);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Add Encounter And Vitals");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(534, 534, 534)
                .addComponent(Submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PatientID5)
                            .addComponent(PatientID6))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EncounterText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PatientID1)
                            .addComponent(PatientID2)
                            .addComponent(PatientID3)
                            .addComponent(PatientID4))
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PulseRateText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BodyTemperatureText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BloodPressureText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(367, 367, 367))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addGap(392, 392, 392)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PatientID1)
                    .addComponent(PatientIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientID2)
                    .addComponent(BloodPressureText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientID3)
                    .addComponent(BodyTemperatureText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientID4)
                    .addComponent(PulseRateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientID6))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncounterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientID5))
                .addGap(99, 99, 99)
                .addComponent(Submit)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String pat =  "";
        String match1 = "";
        String match2 = "";
        //patient validation
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection docConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");
            String DocSql = ("select patientid from patientrecords where patientid = '"+PatientIDText.getText()+"' ");
            PreparedStatement DocPreparedStatement = docConnection.prepareStatement(DocSql);            
            ResultSet commResultSet = DocPreparedStatement.executeQuery();
            while(commResultSet.next())
            {
            pat = commResultSet.getString("patientid");
            }
  
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        
        if(pat.equals("")) {
        JOptionPane.showMessageDialog(null,"Patient ID doesnt exists in the System, please ask Patient to first register");
        PatientIDText.requestFocus();
        return;
        }
        //blood pressure
        if(BloodPressureText.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Blood Pressure Required");
        BloodPressureText.requestFocus();
        return;
        }
        
        //body temperature
        if(BodyTemperatureText.getText().equals("")) {
        JOptionPane.showMessageDialog(null,"Body Temperature Required");
        BodyTemperatureText.requestFocus();
        return;
        }
        
        if(Pattern.matches("[0-9]{2,3}+", BodyTemperatureText.getText())){
        match1 = "1";        
        }      
        
        if(match1.equals("")){
        JOptionPane.showMessageDialog(null,"Body Temperature should range in 2 digits or 3 digits input");
        BodyTemperatureText.requestFocus();
        return;
        }
        
        //pulse rate
        if(PulseRateText.getText().equals("")) {
        JOptionPane.showMessageDialog(null,"Pulse Rate Required");
        PulseRateText.requestFocus();
        return;
        }
        
        if(Pattern.matches("[0-9]{2,3}+", PulseRateText.getText())){
        match2 = "1";        
        }      
        
        if(match2.equals("")){
        JOptionPane.showMessageDialog(null,"Pulse should range in 2 digits or 3 digits input");
        PulseRateText.requestFocus();
        return;
        }
        
        //diagnoses
        if(DiagnosesText.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Diagnoses Required");
        DiagnosesText.requestFocus();
        return;
        }
        
        //date
        String regex = "^(3[01]|[12][0-9]|0[1-9])/(1[0-2]|0[1-9])/[0-9]{4}$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(EncounterText.getText());
        if(matcher.matches()==false){
            JOptionPane.showMessageDialog(null,"Date Not Valid, only dd/mm/yyyy allowed");
            EncounterText.requestFocus();
            return;
        }
 

        
        String patientID = PatientIDText.getText();
        String bloodPressure = BloodPressureText.getText();
        String heartRate = PulseRateText.getText();
        String diagnosis = DiagnosesText.getText();
        String encounter = EncounterText.getText();
        String bodyTemperature = BodyTemperatureText.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection doctorConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");
           
            String DoctorSql = ("UPDATE patientrecords SET blood_pressure = '"+bloodPressure+"', pulse_rate = '"+heartRate+"', body_temperature = '"+bodyTemperature+"', previous_diagnoses = '"+diagnosis+"', encounter_ts = '"+encounter+"' WHERE patientid = '"+patientID+"' ");
            PreparedStatement DoctorPreparedStatement = doctorConnection.prepareStatement(DoctorSql);
            DoctorPreparedStatement.execute();
           
           
             JOptionPane.showMessageDialog(null,"Records added succesfully");
             PatientIDText.setText("");
             BloodPressureText.setText("");
             PulseRateText.setText("");
             DiagnosesText.setText("");
             EncounterText.setText("");
             BodyTemperatureText.setText("");
           
           
   
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
   
    }
    }//GEN-LAST:event_SubmitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new DoctorHomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEncounterAndVitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEncounterAndVitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEncounterAndVitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEncounterAndVitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEncounterAndVitals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BloodPressureText;
    private javax.swing.JTextField BodyTemperatureText;
    private javax.swing.JTextArea DiagnosesText;
    private javax.swing.JTextField EncounterText;
    private javax.swing.JLabel PatientID1;
    private javax.swing.JLabel PatientID2;
    private javax.swing.JLabel PatientID3;
    private javax.swing.JLabel PatientID4;
    private javax.swing.JLabel PatientID5;
    private javax.swing.JLabel PatientID6;
    private javax.swing.JTextField PatientIDText;
    private javax.swing.JTextField PulseRateText;
    private javax.swing.JButton Submit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
