/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmgmt_assignment2;

/**
 *
 * @author maher
 */
public class HospitalAdminHomePage extends javax.swing.JFrame {

    /**
     * Creates new form HospitalAdminHomePage
     */
    public HospitalAdminHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddDoctors = new javax.swing.JButton();
        FireDoctor = new javax.swing.JButton();
        EditDoctor = new javax.swing.JButton();
        ViewRecords = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        AddDoctors.setText("Add Doctor To Hospital");
        AddDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorsActionPerformed(evt);
            }
        });

        FireDoctor.setText("Remove Doctor From Hospital Entry");
        FireDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FireDoctorActionPerformed(evt);
            }
        });

        EditDoctor.setText("View And Edit Doctor Details");
        EditDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDoctorActionPerformed(evt);
            }
        });

        ViewRecords.setText("View Visited Patient Records");
        ViewRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRecordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(AddDoctors)
                .addGap(66, 66, 66)
                .addComponent(FireDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(EditDoctor)
                .addGap(120, 120, 120)
                .addComponent(ViewRecords)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDoctors)
                    .addComponent(FireDoctor)
                    .addComponent(EditDoctor)
                    .addComponent(ViewRecords))
                .addContainerGap(463, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDoctorActionPerformed
        // TODO add your handling code here:
        new HospitalAdminViewEditDoc().setVisible(true);
                dispose();
    }//GEN-LAST:event_EditDoctorActionPerformed

    private void AddDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorsActionPerformed
        // TODO add your handling code here:
          new HospitalAdminAddDoctor().setVisible(true);
                dispose();
    }//GEN-LAST:event_AddDoctorsActionPerformed

    private void FireDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FireDoctorActionPerformed
        // TODO add your handling code here:
        new HospitalAdminRemoveDoctor().setVisible(true);
                dispose();
    }//GEN-LAST:event_FireDoctorActionPerformed

    private void ViewRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRecordsActionPerformed
        // TODO add your handling code here:
        new HospitalAdminViewPatient().setVisible(true);
                dispose();
    }//GEN-LAST:event_ViewRecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalAdminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDoctors;
    private javax.swing.JButton EditDoctor;
    private javax.swing.JButton FireDoctor;
    private javax.swing.JButton ViewRecords;
    // End of variables declaration//GEN-END:variables
}
