/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmgmt_assignment2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import hospitalmgmt_assignment2.PatientLogin;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author maher
 */
public class PatientViewHospital extends javax.swing.JFrame {

    /**
     * Creates new form PatientDashboard
     */
    public PatientViewHospital() {
        initComponents();
        
        Color c = new Color(102,102,102);
        getContentPane().setBackground(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToggleState = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BostonTable = new javax.swing.JTable();
        Boston = new javax.swing.JButton();
        BookHospital = new javax.swing.JTextField();
        BookDoctor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BookDate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        NewYorkTable = new javax.swing.JTable();
        NewYork = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BookDate1 = new com.toedter.calendar.JDateChooser();
        BookDoctor1 = new javax.swing.JTextField();
        BookHospital1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ChicagoTable = new javax.swing.JTable();
        Chicago = new javax.swing.JButton();
        BookHospital2 = new javax.swing.JTextField();
        BookDoctor2 = new javax.swing.JTextField();
        BookDate2 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        BostonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Communities", "Hospitals", "Doctors", "Specialisation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BostonTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BostonTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BostonTable);

        Boston.setText("Show Hospitals and Doctors");
        Boston.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BostonActionPerformed(evt);
            }
        });

        jLabel1.setText("Hospital");

        jLabel2.setText("Doctor");

        jButton1.setText("Book Appointment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Date");

        jButton4.setText("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setText("View Hospitals");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(141, 141, 141)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BookDate, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(BookDoctor)
                    .addComponent(BookHospital))
                .addGap(419, 419, 419))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(493, 493, 493)
                        .addComponent(Boston))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(517, 517, 517)
                        .addComponent(jButton1)))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton5)
                .addGap(380, 380, 380)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Boston)
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addComponent(BookDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(103, 103, 103)
                .addComponent(jButton1)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Boston", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        NewYorkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Communities", "Hospitals", "Doctors", "Specialisation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        NewYorkTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewYorkTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(NewYorkTable);

        NewYork.setText("Show Hospitals and Doctors");
        NewYork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewYorkActionPerformed(evt);
            }
        });

        jButton2.setText("Book Appointment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Hospital");

        jLabel5.setText("Doctor");

        jLabel6.setText("Date");

        jButton6.setText("LOGOUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel12.setText("View Hospitals");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(491, 491, 491)
                        .addComponent(NewYork))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(141, 141, 141)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BookDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BookDoctor1)
                                    .addComponent(BookHospital1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jButton2)))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton7)
                .addGap(387, 387, 387)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(93, 93, 93))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel12)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(NewYork)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookHospital1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookDoctor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(51, 51, 51)
                        .addComponent(BookDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(103, 103, 103)
                .addComponent(jButton2)
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("New York", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        ChicagoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Communities", "Hospitals", "Doctors", "Specialisation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ChicagoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChicagoTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ChicagoTable);

        Chicago.setText("Show Hospitals and Doctors");
        Chicago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChicagoActionPerformed(evt);
            }
        });

        jButton3.setText("Book Appointment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Date");

        jLabel8.setText("Doctor");

        jLabel9.setText("Hospital");

        jButton8.setText("LOGOUT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("BACK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel11.setText("View Hospitals");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(Chicago))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(141, 141, 141)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BookDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BookDoctor2)
                                    .addComponent(BookHospital2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jButton3)))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jButton9)
                .addGap(362, 362, 362)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(97, 97, 97))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton9)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(Chicago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookHospital2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookDoctor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(51, 51, 51)
                        .addComponent(BookDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(103, 103, 103)
                .addComponent(jButton3)
                .addGap(104, 104, 104))
        );

        jTabbedPane1.addTab("Chicago", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentShown

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void NewYorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewYorkActionPerformed
        // TODO add your handling code here:
        try{                                       
            Class.forName("com.mysql.jdbc.Driver");
            Connection PatientDConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");
            Statement PatientDStatement = (Statement) PatientDConnection.createStatement();
            String PatientDSql = ("Select community, hospital, doctor, specialisation from hospitals where city = 'New York' ");
            
            PreparedStatement PatientPS = PatientDConnection.prepareStatement(PatientDSql);
            ResultSet PatientDResult = PatientPS.executeQuery();
            DefaultTableModel HospitalTableModel = (DefaultTableModel)NewYorkTable.getModel();
            HospitalTableModel.setRowCount(0);
            while(PatientDResult.next()){
            Object newyork[]=   { PatientDResult.getString("community"), 
                PatientDResult.getString("hospital"), 
                PatientDResult.getString("doctor"), 
                PatientDResult.getString("specialisation") 
                }    ;
            
            HospitalTableModel.addRow(newyork);
        }                       
                
                
        
        }catch(Exception e)   {                                       
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_NewYorkActionPerformed

    private void BostonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BostonActionPerformed
        // TODO add your handling code here:
        try{                                       
            Class.forName("com.mysql.jdbc.Driver");
            Connection PatientDConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");
            Statement PatientDStatement = (Statement) PatientDConnection.createStatement();
            String PatientDSql = ("Select community, hospital, doctor, specialisation from hospitals where city = 'Boston' ");
            
            PreparedStatement PatientPS = PatientDConnection.prepareStatement(PatientDSql);
            ResultSet PatientDResult = PatientPS.executeQuery();
            DefaultTableModel HospitalTableModel = (DefaultTableModel)BostonTable.getModel();
            HospitalTableModel.setRowCount(0);
            while(PatientDResult.next()){
            Object boston[]=   { PatientDResult.getString("community"), 
                PatientDResult.getString("hospital"), 
                PatientDResult.getString("doctor"), 
                PatientDResult.getString("specialisation") 
                }    ;
            
            HospitalTableModel.addRow(boston);
        }                       
                
                
        
        }catch(Exception e)   {                                       
        JOptionPane.showMessageDialog(null, e);
        }                                      
        
    }//GEN-LAST:event_BostonActionPerformed

    private void ChicagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChicagoActionPerformed
        // TODO add your handling code here:
         try{                                       
            Class.forName("com.mysql.jdbc.Driver");
            Connection PatientDConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");
            Statement PatientDStatement = (Statement) PatientDConnection.createStatement();
            String PatientDSql = ("Select community, hospital, doctor, specialisation from hospitals where city = 'Chicago' ");
            
            PreparedStatement PatientPS = PatientDConnection.prepareStatement(PatientDSql);
            ResultSet PatientDResult = PatientPS.executeQuery();
            DefaultTableModel HospitalTableModel = (DefaultTableModel)ChicagoTable.getModel();
            HospitalTableModel.setRowCount(0);
            while(PatientDResult.next()){
            Object chicago[]=   { PatientDResult.getString("community"), 
                PatientDResult.getString("hospital"), 
                PatientDResult.getString("doctor"), 
                PatientDResult.getString("specialisation") 
                }    ;
            
            HospitalTableModel.addRow(chicago);
        }                       
                
                
        
        }catch(Exception e)   {                                       
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ChicagoActionPerformed

    private void BostonTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BostonTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel HospitalTableModel = (DefaultTableModel)BostonTable.getModel();
            int selectedRowIndex = BostonTable.getSelectedRow();
            
            BookHospital.setText((String) HospitalTableModel.getValueAt(selectedRowIndex, 1));          
            BookDoctor.setText((String) HospitalTableModel.getValueAt(selectedRowIndex, 2));
            
    }//GEN-LAST:event_BostonTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String doctorID1 = "";
        String HospitalApp = BookHospital.getText();
        String DoctorApp = BookDoctor.getText();
       java.util.Date DateApp = BookDate.getCalendar().getTime();
        String PatientID = PatientLogin.PatientUsernameField.getText();
        
        
        try{  
        Class.forName("com.mysql.jdbc.Driver");
        Connection DoctorIDConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");           
        Statement DoctorIDStatement = (Statement) DoctorIDConnection.createStatement();
        String DoctorID = ("Select doctorid from hospitals where doctor = '"+DoctorApp+"' ");
        
        
        PreparedStatement DoctorIDPS = DoctorIDConnection.prepareStatement(DoctorID);
        ResultSet DoctorIDResult = DoctorIDPS.executeQuery(); 
        
        while(DoctorIDResult.next()){
             doctorID1 =    DoctorIDResult.getString("doctorid");
        
            
        } }   catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
   
    }
        
        
        
       DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss"); 
       String DateApp1 = dateFormat.format(DateApp);
        
        try{   
            
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection PatientAConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");
            Statement PatientAStatement = (Statement) PatientAConnection.createStatement();
            
            String PatientASql = "Insert into appointments values (?,?,?,?,?)";
            PreparedStatement PatientApp = PatientAConnection.prepareStatement(PatientASql);
            
            PatientApp.setString(1, PatientID);
            PatientApp.setString(2, HospitalApp);           
            PatientApp.setString(3, DoctorApp);
            PatientApp.setString(4, DateApp1);
            PatientApp.setString(5,doctorID1);
            PatientApp.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Appointment Booked Succesfully");
            PatientAConnection.close();

            
        }    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
   
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        String doctorID1 = "";
        String HospitalApp = BookHospital1.getText();
        String DoctorApp = BookDoctor1.getText();
       java.util.Date DateApp = BookDate1.getCalendar().getTime();
        String PatientID = PatientLogin.PatientUsernameField.getText();
        
        
        try{  
        Class.forName("com.mysql.jdbc.Driver");
        Connection DoctorIDConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");           
        Statement DoctorIDStatement = (Statement) DoctorIDConnection.createStatement();
        String DoctorID = ("Select doctorid from hospitals where doctor = '"+DoctorApp+"' ");
        
        
        PreparedStatement DoctorIDPS = DoctorIDConnection.prepareStatement(DoctorID);
        ResultSet DoctorIDResult = DoctorIDPS.executeQuery(); 
        
        while(DoctorIDResult.next()){
             doctorID1 =    DoctorIDResult.getString("doctorid");
        
            
        } }   catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
   
    }
        
        
        
       DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss"); 
       String DateApp1 = dateFormat.format(DateApp);
        
        try{   
            
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection PatientAConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");
            Statement PatientAStatement = (Statement) PatientAConnection.createStatement();
            
            String PatientASql = "Insert into appointments values (?,?,?,?,?)";
            PreparedStatement PatientApp = PatientAConnection.prepareStatement(PatientASql);
            
            PatientApp.setString(1, PatientID);
            PatientApp.setString(2, HospitalApp);           
            PatientApp.setString(3, DoctorApp);
            PatientApp.setString(4, DateApp1);
            PatientApp.setString(5,doctorID1);
            PatientApp.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Appointment Booked Succesfully");
            PatientAConnection.close();

            
        }    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
   
    }

        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String doctorID1 = "";
        String HospitalApp = BookHospital2.getText();
        String DoctorApp = BookDoctor2.getText();
        java.util.Date DateApp = BookDate2.getCalendar().getTime();
        String PatientID = PatientLogin.PatientUsernameField.getText();
        
        
        try{  
        Class.forName("com.mysql.jdbc.Driver");
        Connection DoctorIDConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");           
        Statement DoctorIDStatement = (Statement) DoctorIDConnection.createStatement();
        String DoctorID = ("Select doctorid from hospitals where doctor = '"+DoctorApp+"' ");
        
        
        PreparedStatement DoctorIDPS = DoctorIDConnection.prepareStatement(DoctorID);
        ResultSet DoctorIDResult = DoctorIDPS.executeQuery(); 
        
        while(DoctorIDResult.next()){
             doctorID1 =    DoctorIDResult.getString("doctorid");
        
            
        } }   catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
   
    }
        
        
        
       DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss"); 
       String DateApp1 = dateFormat.format(DateApp);
        
        try{   
            
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection PatientAConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");
            Statement PatientAStatement = (Statement) PatientAConnection.createStatement();
            
            String PatientASql = "Insert into appointments values (?,?,?,?,?)";
            PreparedStatement PatientApp = PatientAConnection.prepareStatement(PatientASql);
            
            PatientApp.setString(1, PatientID);
            PatientApp.setString(2, HospitalApp);           
            PatientApp.setString(3, DoctorApp);
            PatientApp.setString(4, DateApp1);
            PatientApp.setString(5,doctorID1);
            PatientApp.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Appointment Booked Succesfully");
            PatientAConnection.close();

            
        }    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
   
    }

        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void NewYorkTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewYorkTableMouseClicked
        // TODO add your handling code here:
          DefaultTableModel HospitalTableModel = (DefaultTableModel)NewYorkTable.getModel();
            int selectedRowIndex = NewYorkTable.getSelectedRow();
            
            BookHospital1.setText((String) HospitalTableModel.getValueAt(selectedRowIndex, 1));          
            BookDoctor1.setText((String) HospitalTableModel.getValueAt(selectedRowIndex, 2));
      
    }//GEN-LAST:event_NewYorkTableMouseClicked

    private void ChicagoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChicagoTableMouseClicked
        // TODO add your handling code here:
          DefaultTableModel HospitalTableModel = (DefaultTableModel)ChicagoTable.getModel();
            int selectedRowIndex = ChicagoTable.getSelectedRow();
            
            BookHospital2.setText((String) HospitalTableModel.getValueAt(selectedRowIndex, 1));          
            BookDoctor2.setText((String) HospitalTableModel.getValueAt(selectedRowIndex, 2));
      
    }//GEN-LAST:event_ChicagoTableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new PatientHomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new PatientHomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         new HomePage().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        new PatientHomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientViewHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientViewHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientViewHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientViewHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientViewHospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser BookDate;
    private com.toedter.calendar.JDateChooser BookDate1;
    private com.toedter.calendar.JDateChooser BookDate2;
    private javax.swing.JTextField BookDoctor;
    private javax.swing.JTextField BookDoctor1;
    private javax.swing.JTextField BookDoctor2;
    private javax.swing.JTextField BookHospital;
    private javax.swing.JTextField BookHospital1;
    private javax.swing.JTextField BookHospital2;
    private javax.swing.JButton Boston;
    private javax.swing.JTable BostonTable;
    private javax.swing.JButton Chicago;
    private javax.swing.JTable ChicagoTable;
    private javax.swing.JButton NewYork;
    private javax.swing.JTable NewYorkTable;
    private javax.swing.ButtonGroup ToggleState;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
