/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmgmt_assignment2;

import hospitalmgmt_assignment2.PatientLogin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maher
 */
public class PatientViewRecords extends javax.swing.JFrame {

    /**
     * Creates new form PatientViewRecords
     */
    public PatientViewRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PatientRecords = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        PatientRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age ", "House", "Community", "Blood Pressure", "Body Temperature", "Pulse Rate", "Previous Diagnoses", "Encounter Timestamp", "Hospital "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(PatientRecords);
        if (PatientRecords.getColumnModel().getColumnCount() > 0) {
            PatientRecords.getColumnModel().getColumn(1).setPreferredWidth(10);
            PatientRecords.getColumnModel().getColumn(4).setPreferredWidth(10);
            PatientRecords.getColumnModel().getColumn(5).setPreferredWidth(10);
            PatientRecords.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(448, 448, 448))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
        
        String s = PatientLogin.PatientUsernameField.getText();
        
        
        try{                                       
            Class.forName("com.mysql.jdbc.Driver");
            Connection PatientRConnection = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root", "");
            Statement PatientRStatement = (Statement) PatientRConnection.createStatement();
            
            String PatientRSql = ("Select name, age, house, community, blood_pressure, body_temperature, pulse_rate, previous_diagnoses, "
                    + "encounter_ts, hospital_encounter from patientrecords "
                    + "WHERE patientid = '" + s + "' ");
            
            
            PreparedStatement PatientPS = PatientRConnection.prepareStatement(PatientRSql);
            ResultSet PatientRResult = PatientPS.executeQuery();
            DefaultTableModel PatientTableModel = (DefaultTableModel)PatientRecords.getModel();
            PatientTableModel.setRowCount(0);
            while(PatientRResult.next()){
            Object patient[]=   { PatientRResult.getString("name"), 
                PatientRResult.getString("age"), 
                PatientRResult.getString("house"), 
                PatientRResult.getString("community"),
                PatientRResult.getString("blood_pressure"), 
                PatientRResult.getString("body_temperature"), 
                PatientRResult.getString("pulse_rate"), 
                PatientRResult.getString("previous_diagnoses"),       
                PatientRResult.getString("encounter_ts"), 
                PatientRResult.getString("hospital_encounter"),
                }    ;
            
            PatientTableModel.addRow(patient);
        }                       
                
                
        
        }catch(Exception e)   {                                       
        JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_formWindowActivated
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientViewRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PatientRecords;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
